<Project>
	<PropertyGroup>
		<LangVersion>preview</LangVersion>
		<Version>3.10</Version>
		<TargetFrameworks>net35;net452;netstandard1.0;netstandard2.0;netstandard2.1;net5.0;net6.0;net7.0;net8.0;net9.0;net10.0;net11.0</TargetFrameworks>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<IncludeSymbols>true</IncludeSymbols>
		<Authors>百小僧</Authors>
		<Company>百签科技（广东）有限公司</Company>
		<Product>TimeCrontab</Product>
		<Copyright>© 2020-2026 百小僧及百签科技（广东）有限公司</Copyright>
		<RepositoryUrl>https://gitee.com/dotnetchina/TimeCrontab</RepositoryUrl>
		<RepositoryType>Gitee</RepositoryType>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://gitee.com/dotnetchina/TimeCrontab</PackageProjectUrl>
		<PackageTags>Crons;Crontab;TimeCrontab;百小僧;Monk;MonkSoul;ASP.NET;ASP.NET Core;.NET;.NET Core;.NET5;.NET6;.NET7;.NET8;Framework;dotNET;dotNET China;Web;Cross Platform</PackageTags>
		<PackageOutputPath>../nupkgs</PackageOutputPath>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSource>true</EmbedUntrackedSource>
		<EmbedAllSources>true</EmbedAllSources>
		<DocumentationFile>$(MSBuildProjectName).xml</DocumentationFile>
		<PackageIcon>icon.png</PackageIcon>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\README.md" Pack="true" PackagePath="\"/>
		<None Include="..\..\README.zh.md" Pack="true" PackagePath="\"/>
		<None Include="..\Directory.Build.props" Pack="true" PackagePath="\"/>
		<None Include="..\icon.png" Pack="true" PackagePath="\"/>
	</ItemGroup>

</Project>